import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { UtilisateursOverviewComponent } from '../../components/utilisateurs-overview/utilisateurs-overview.component';
import { MainLayoutComponent } from 'src/app/Core/layouts/main-layout/main-layout.component';

@Component({
  selector: 'app-index-view',
  standalone: true,
  imports: [CommonModule, MainLayoutComponent, UtilisateursOverviewComponent],
  templateUrl: './index-view.component.html',
  styleUrls: ['./index-view.component.scss'],
})
export class IndexViewComponent {
  columns = [
    { key: 'nom', label: 'Nom' },
    { key: 'prenoms', label: 'Prenoms' },
    { key: 'numero', label: 'Numéro' },
    { key: 'email', label: 'Email' },
    { key: 'role', label: 'Rôle' },
    { key: 'dateCreation', label: 'Date de creation' },
    { key: 'statut', label: 'Statut' },
  ];

  data = [
    {
      id: '1',
      nom: 'Fofana',
      prenoms: 'Amed',
      numero: '07 875 092 57',
      email: 'fofanamed@gmail.com',
      role: 'Manager',
      dateCreation: '21/02/2025',
      statut: 'Actif',
    },
    {
      id: '2',
      nom: 'Diallo',
      prenoms: 'Sophie',
      numero: '07 123 456 78',
      email: 'sophie.diallo@gmail.com',
      role: 'Manager',
      dateCreation: '21/02/2025',
      statut: 'Inactif',
    },
    {
      id: '3',
      nom: 'Koné',
      prenoms: 'Ibrahim',
      numero: '07 234 567 89',
      email: 'ibrahim.kone@gmail.com',
      role: 'Manager',
      dateCreation: '21/02/2025',
      statut: 'En attente',
    },
    {
      id: '4',
      nom: 'Touré',
      prenoms: 'Marie',
      numero: '07 345 678 90',
      email: 'marie.toure@gmail.com',
      role: 'Manager',
      dateCreation: '21/02/2025',
      statut: 'Rejeté',
    },
    {
      id: '5',
      nom: 'Ouattara',
      prenoms: 'Ali',
      numero: '07 456 789 01',
      email: 'ali.ouattara@gmail.com',
      role: 'Employé',
      dateCreation: '22/02/2025',
      statut: 'Actif',
    },
    {
      id: '6',
      nom: 'Coulibaly',
      prenoms: 'Fatou',
      numero: '07 567 890 12',
      email: 'fatou.coulibaly@gmail.com',
      role: 'Employé',
      dateCreation: '22/02/2025',
      statut: 'Inactif',
    },
    {
      id: '7',
      nom: 'Bamba',
      prenoms: 'Karim',
      numero: '07 678 901 23',
      email: 'karim.bamba@gmail.com',
      role: 'Directeur',
      dateCreation: '23/02/2025',
      statut: 'Actif',
    },
    {
      id: '8',
      nom: 'Diomandé',
      prenoms: 'Aïcha',
      numero: '07 789 012 34',
      email: 'aicha.diomande@gmail.com',
      role: 'Manager',
      dateCreation: '23/02/2025',
      statut: 'En attente',
    },
    {
      id: '9',
      nom: 'Sanogo',
      prenoms: 'Moussa',
      numero: '07 890 123 45',
      email: 'moussa.sanogo@gmail.com',
      role: 'Employé',
      dateCreation: '24/02/2025',
      statut: 'Rejeté',
    },
    {
      id: '10',
      nom: 'Traoré',
      prenoms: 'Nadia',
      numero: '07 901 234 56',
      email: 'nadia.traore@gmail.com',
      role: 'Employé',
      dateCreation: '24/02/2025',
      statut: 'Actif',
    },
    {
      id: '11',
      nom: 'Kouadio',
      prenoms: 'Jean',
      numero: '07 012 345 67',
      email: 'jean.kouadio@gmail.com',
      role: 'Manager',
      dateCreation: '25/02/2025',
      statut: 'Inactif',
    },
    {
      id: '12',
      nom: 'Yao',
      prenoms: 'Serge',
      numero: '07 123 456 78',
      email: 'serge.yao@gmail.com',
      role: 'Employé',
      dateCreation: '25/02/2025',
      statut: 'Actif',
    },
    {
      id: '13',
      nom: 'Koffi',
      prenoms: 'Paul',
      numero: '07 234 567 89',
      email: 'paul.koffi@gmail.com',
      role: 'Directeur',
      dateCreation: '26/02/2025',
      statut: 'En attente',
    },
    {
      id: '14',
      nom: 'Gon',
      prenoms: 'Eric',
      numero: '07 345 678 90',
      email: 'eric.gon@gmail.com',
      role: 'Manager',
      dateCreation: '26/02/2025',
      statut: 'Rejeté',
    },
    {
      id: '15',
      nom: 'Tano',
      prenoms: 'Cécile',
      numero: '07 456 789 01',
      email: 'cecile.tano@gmail.com',
      role: 'Employé',
      dateCreation: '27/02/2025',
      statut: 'Actif',
    },
    {
      id: '16',
      nom: 'Ble',
      prenoms: 'David',
      numero: '07 567 890 12',
      email: 'david.ble@gmail.com',
      role: 'Employé',
      dateCreation: '27/02/2025',
      statut: 'Inactif',
    },
    {
      id: '17',
      nom: 'Etté',
      prenoms: 'Julien',
      numero: '07 678 901 23',
      email: 'julien.ette@gmail.com',
      role: 'Directeur',
      dateCreation: '28/02/2025',
      statut: 'Actif',
    },
    {
      id: '18',
      nom: 'Kouakou',
      prenoms: 'Brigitte',
      numero: '07 789 012 34',
      email: 'brigitte.kouakou@gmail.com',
      role: 'Manager',
      dateCreation: '28/02/2025',
      statut: 'En attente',
    },
    {
      id: '19',
      nom: 'Zadi',
      prenoms: 'Marcel',
      numero: '07 890 123 45',
      email: 'marcel.zadi@gmail.com',
      role: 'Employé',
      dateCreation: '01/03/2025',
      statut: 'Rejeté',
    },
    {
      id: '20',
      nom: 'Kadio',
      prenoms: 'Luc',
      numero: '07 901 234 56',
      email: 'luc.kadio@gmail.com',
      role: 'Employé',
      dateCreation: '01/03/2025',
      statut: 'Actif',
    },
  ];

  statusColors = {
    Inactif: 'sleep',
    Actif: 'go',
    'En attente': 'cancel',
    Rejeté: 'no-go',
  };
}
